<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="5" failures="0" skipped="0" tests="5" time="2.881" timestamp="2025-04-25T07:43:32.269406+00:00" hostname="831acda2f8db"><testcase classname="" name="tests.services.test_embedding_service" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/MLOps_AWS/rag-app/tests/services/test_embedding_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/services/test_embedding_service.py:2: in &lt;module&gt;
    from server.src.services.embedding_service import get_embedding
E   ModuleNotFoundError: No module named 'server.src.services.embedding_service'</error></testcase><testcase classname="" name="tests.services.test_generation_service" time="0.000"><error message="collection failure">tests/services/test_generation_service.py:9: in &lt;module&gt;
    from server.src.services.generation_service import generate_response, call_llm
server/src/services/generation_service.py:4: in &lt;module&gt;
    from server.src.config import settings
server/src/config.py:43: in &lt;module&gt;
    settings = Settings()
/home/vscode/.cache/pypoetry/virtualenvs/rag-app-KRqb-5lH-py3.12/lib/python3.12/site-packages/pydantic_settings/main.py:176: in __init__
    super().__init__(
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
E   opik_project_name
E     Extra inputs are not permitted [type=extra_forbidden, input_value='rag-app', input_type=str]
E       For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden</error></testcase><testcase classname="" name="tests.services.test_llm_service" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/MLOps_AWS/rag-app/tests/services/test_llm_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/services/test_llm_service.py:2: in &lt;module&gt;
    from server.src.services.llm_service import generate_response
server/src/services/llm_service.py:1: in &lt;module&gt;
    from langchain.llms import OpenAI
E   ModuleNotFoundError: No module named 'langchain'</error></testcase><testcase classname="" name="tests.services.test_rag_service" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/MLOps_AWS/rag-app/tests/services/test_rag_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/services/test_rag_service.py:2: in &lt;module&gt;
    from server.src.services.rag_service import process_query
server/src/services/rag_service.py:1: in &lt;module&gt;
    from .embedding_service import get_embedding
E   ModuleNotFoundError: No module named 'server.src.services.embedding_service'</error></testcase><testcase classname="" name="tests.services.test_retrieval_service" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/MLOps_AWS/rag-app/tests/services/test_retrieval_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/services/test_retrieval_service.py:2: in &lt;module&gt;
    from server.src.services.retrieval_service import retrieve_top_k_chunks, get_db_connection, retrieve_relevant_chunks
server/src/services/retrieval_service.py:9: in &lt;module&gt;
    from langchain.vectorstores import FAISS
E   ModuleNotFoundError: No module named 'langchain'</error></testcase></testsuite></testsuites>